name: Install check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install check
      run: |
        cd API
        sudo python3 setup.py install
