name: Train test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Train
      run: |
        cd API
        sudo python3 setup.py install
        cd ..
        cd Scripts
        python3 Train.py
        ls
